version: "3"

services:

  mcserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcserver-1.12.2-gtceucraft
    image: mcserver/1.12.2/gtceucraft:latest
    entrypoint: 
      - java
      - -server
      - -Dfile.encoding=utf-8
      - -XshowSettings:vm
      - -Xms6G
      - -Xmx6G
      - -XX:+UseG1GC
      - -XX:+UnlockExperimentalVMOptions
      - -XX:G1HeapRegionSize=16m
      - -XX:+DisableExplicitGC
      - -XX:TargetSurvivorRatio=90
      - -XX:G1NewSizePercent=50
      - -XX:G1MaxNewSizePercent=80
      - -XX:G1MixedGCLiveThresholdPercent=35
      - -XX:+AlwaysPreTouch
      - -XX:+ParallelRefProcEnabled
      - -jar
      - /mcserver/mohist-server.jar
    volumes:
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/world/:/mcserver/world/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/logs/:/mcserver/logs/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/mods/:/mcserver/mods/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/libraries/:/mcserver/libraries/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/plugins/:/mcserver/plugins/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/config/:/mcserver/config/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/backups/:/mcserver/backups/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/journeymap/:/mcserver/journeymap/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/mohist-config/:/mcserver/mohist-config/
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/server.properties:/mcserver/server.properties
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/ops.json:/mcserver/ops.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/banned-ips.json:/mcserver/banned-ips.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/banned-players.json:/mcserver/banned-players.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/paper.yml:/mcserver/paper.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/permissions.yml:/mcserver/permissions.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/whitelist.json:/mcserver/whitelist.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/usercache.json:/mcserver/usercache.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/usernamecache.json:/mcserver/usernamecache.json
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/bukkit.yml:/mcserver/bukkit.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/spigot.yml:/mcserver/spigot.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/commands.yml:/mcserver/commands.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/help.yml:/mcserver/help.yml
      - /sandisk/volumes/mcserver/1.12.2/gtceucraft/eula.txt:/mcserver/eula.txt
    ports:
      - "26947:26947"
    restart: unless-stopped
    network_mode: "bridge"
    stdin_open: true
    tty: true
    privileged: true
