version: "3.9"

services:

  mcserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcserver-1.12.2-gtceucraft
    image: mcserver/1.12.2/gtceucraft:latest
    entrypoint: 
      - java
      - -server
      - -XshowSettings:vm
      - -Xms4G
      - -Xmx4G
      ################### CMS Config ###################
      - -XX:+UseConcMarkSweepGC
      - -XX:ParallelGCThreads=4
      - -XX:ConcGCThreads=1
      - -XX:+CMSClassUnloadingEnabled
      - -XX:+CMSIncrementalMode
      - -XX:+CMSScavengeBeforeRemark
      - -XX:+UseCMSInitiatingOccupancyOnly
      - -XX:CMSInitiatingOccupancyFraction=70
      - -XX:CMSFullGCsBeforeCompaction=5
      - -XX:MaxGCPauseMillis=100
      - -XX:+ExplicitGCInvokesConcurrent
      - -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
      - -XX:+UseFastAccessorMethods
      - -XX:+DisableExplicitGC
      - -XX:TargetSurvivorRatio=90
      ##################################################
      ################### G1GC Config ##################
      # - -XX:+UseG1GC
      # - -XX:+UnlockExperimentalVMOptions
      # - -XX:G1HeapRegionSize=32m
      # - -XX:+DisableExplicitGC
      # - -XX:TargetSurvivorRatio=80
      # - -XX:G1NewSizePercent=50
      # - -XX:G1MaxNewSizePercent=80
      # - -XX:G1MixedGCLiveThresholdPercent=35
      # - -XX:+AlwaysPreTouch
      # - -XX:+ParallelRefProcEnabled
      # - -XX:+UseStringDeduplication # Testing
      ################################################
      # - -XX:+PrintGCApplicationStoppedTime
      # - -XX:+PrintTenuringDistribution
      # - -XX:+PrintPromotionFailure
      # - -XX:+PrintGCTimeStamps
      # - -XX:+PrintGCDetails
      # - -XX:+PrintGCDateStamps
      # - -XX:+PrintHeapAtGC
      ################################################
      - -Dfile.encoding=utf-8
      - -jar
      - mohist-server.jar
    volumes:
      ###Big files and logs###
      - ${BIG_FILE_PATH}/world/:/mcserver/world/
      - ${BIG_FILE_PATH}/backups/:/mcserver/backups/
      - ${BIG_FILE_PATH}/logs/:/mcserver/logs/
      - ${BIG_FILE_PATH}/libraries/:/mcserver/libraries/
      - ${BIG_FILE_PATH}/mods/:/mcserver/mods/
      - ${BIG_FILE_PATH}/journeymap/:/mcserver/journeymap/
      ###Files from GitHub###
      - ${GIT_FILE_PATH}/plugins/:/mcserver/plugins/
      - ${GIT_FILE_PATH}/config/:/mcserver/config/
      - ${GIT_FILE_PATH}/crash-reports/:/mcserver/crash-reports/
      - ${GIT_FILE_PATH}/mohist-config/:/mcserver/mohist-config/
      - ${GIT_FILE_PATH}/server.properties:/mcserver/server.properties
      - ${GIT_FILE_PATH}/ops.json:/mcserver/ops.json
      - ${GIT_FILE_PATH}/banned-ips.json:/mcserver/banned-ips.json
      - ${GIT_FILE_PATH}/banned-players.json:/mcserver/banned-players.json
      - ${GIT_FILE_PATH}/paper.yml:/mcserver/paper.yml
      - ${GIT_FILE_PATH}/permissions.yml:/mcserver/permissions.yml
      - ${GIT_FILE_PATH}/whitelist.json:/mcserver/whitelist.json
      - ${GIT_FILE_PATH}/usercache.json:/mcserver/usercache.json
      - ${GIT_FILE_PATH}/usernamecache.json:/mcserver/usernamecache.json
      - ${GIT_FILE_PATH}/bukkit.yml:/mcserver/bukkit.yml
      - ${GIT_FILE_PATH}/spigot.yml:/mcserver/spigot.yml
      - ${GIT_FILE_PATH}/commands.yml:/mcserver/commands.yml
      - ${GIT_FILE_PATH}/help.yml:/mcserver/help.yml
      - ${GIT_FILE_PATH}/eula.txt:/mcserver/eula.txt:ro
    ports:
      - "26947:26947"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        # max_attempts: 2
        window: 20s
    network_mode: "bridge"
    stdin_open: true
    tty: true
    privileged: false