version: "3.9"

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 64M
        reservations:
          memory: 32M
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    privileged: false
